{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "prometheus.server.fullname" . }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "prometheus.name" . }}
      component: "{{ .Values.server.name }}"
      release: {{ .Release.Name }}
  ingress:
    - ports:
      - port: 9090
{{- end }}
